risinglightdb/risinglight

- README.md
- docs/00-develop.md
> docs: update links in repo

- Cargo.lock
- Cargo.toml
- src/array/data_chunk.rs
comfy-table is still actively maintained.
Signed-off-by: Chojan Shang <psiace@outlook.com>
> refactor(datachunk): replace prettytable-rs with comfy-table

- src/executor/aggregation/sum.rs
- src/storage/secondary/block/varchar_block_builder.rs
> chore: remove unnecessary attributes

- Cargo.lock
- Cargo.toml
- src/executor/hash_agg.rs
Part of #348
Signed-off-by: TennyZhuang <zty0826@gmail.com>
> feat(executor): split chunks in hash_agg

- src/db.rs
- src/storage/secondary/block.rs
- src/storage/secondary/block/char_block_builder.rs
- src/storage/secondary/block/primitive_block_builder.rs
- src/storage/secondary/block/primitive_nullable_block_builder.rs
- src/storage/secondary/block/varchar_block_builder.rs
- src/storage/secondary/statistics.rs
- src/storage/secondary/statistics/statistics_builder.rs
- tests/sql/catalog.slt
- tests/sql/statistics.slt
- tests/sqllogictest.rs
close https://github.com/risinglightdb/risinglight/issues/347
> chore(storage): add statistics test and catalog test

- src/optimizer/logical_plan_rewriter/arith_expr_simplification.rs
- src/optimizer/logical_plan_rewriter/bool_expr_simplification.rs
- src/optimizer/logical_plan_rewriter/constant_folding.rs
- src/optimizer/logical_plan_rewriter/constant_moving.rs
- src/optimizer/logical_plan_rewriter/mod.rs
- src/optimizer/mod.rs
Signed-off-by: MingjiHan <mingjihan@umass.edu>
> feat(optimizer): activate rules

- src/binder/statement/insert.rs
> feat(binder): insert type cast on implicit type conversion

- .github/workflows/bench.yml
> ci: run bench on ubuntu-latest

- src/db.rs
- src/optimizer/logical_plan_rewriter/arith_expr_simplification.rs
Signed-off-by: MingjiHan <mingjihan@umass.edu>
> feat(optimizer): add optimizer test framework

- src/executor/table_scan.rs
part of https://github.com/risinglightdb/risinglight/issues/366
> feat(storage): support multi-thread execution for table scan

- .gitignore
- Makefile
- docs/01-tpch.md
- tests/sql/tpch/import.sql
- tests/sql/tpch/q1.sql
- tests/sql/tpch/q10.sql
- tests/sql/tpch/q3.sql
- tests/sql/tpch/q5.sql
- tests/sql/tpch/q6.sql
> chore(docs): update instructions to run TPC-H

- README.md
This PR adds Slack community and WeChat community link. Welcome to join our message channels!
> docs: add community links

- src/lib.rs
- src/storage/memory/iterator.rs
- src/storage/mod.rs
- src/storage/secondary/txn_iterator.rs
Part of #389 
Signed-off-by: TennyZhuang <zty0826@gmail.com>
> refactor(storage): use static async trait in TxnIterator

- src/storage/secondary/column.rs
- src/storage/secondary/column/concrete_column_iterator.rs
> refactor(storage): use static async trait in ColumnIterator

- src/storage/memory/mod.rs
- src/storage/mod.rs
- src/storage/secondary/mod.rs
Part of https://github.com/risinglightdb/risinglight/issues/389
Issue Number: close https://github.com/risinglightdb/risinglight/issues/392
> refactor(storage): remove async_trait for Storage trait

- src/storage/memory/transaction.rs
- src/storage/mod.rs
- src/storage/secondary/transaction.rs
Part of #389
Issue Number: close #395
> refactor(storage): remove async_trait for Transaction trait

- docs/00-develop.md
To close https://github.com/risinglightdb/risinglight/issues/406
> fix(docs): enable debug logs

- CONTRIBUTING.md
- Cargo.lock
- README.md
> chore: bump dependencies and update readme

- src/storage/secondary/rowset/mem_rowset.rs
- src/storage/secondary/table.rs
- src/storage/secondary/transaction.rs
> refactor(storage): build rowset while appending data in ColumnMemTable

- Cargo.lock
- Cargo.toml
- src/storage/secondary/storage.rs
> chore: bump dependencies moka, parking_lot, async_recursion

- README.md
> misc: Update README.md

- CODE_OF_CONDUCT.md
> docs: create code-of-conduct

- Cargo.lock
- Cargo.toml
- src/array/primitive_array/simd.rs
- src/binder/expression/mod.rs
- src/storage/secondary/block/primitive_nullable_block_builder.rs
- src/storage/secondary/block/primitive_nullable_block_iterator.rs
- src/storage/secondary/column/primitive_column_factory.rs
- src/storage/secondary/delete_vector.rs
Issue Number: close https://github.com/risinglightdb/risinglight/issues/416
> deps: upgrade bitvec to 1.0

- src/array/data_chunk.rs
- src/db.rs
- src/optimizer/plan_nodes/logical_aggregate.rs
- src/optimizer/plan_nodes/logical_projection.rs
Close #231 
This PR depends on #427
> chore: add column name to output

- src/array/data_chunk.rs
- src/executor/create.rs
- src/executor/explain.rs
- src/executor/insert.rs
- src/main.rs
closes https://github.com/risinglightdb/risinglight/issues/434
> human-readable message for create & insert & explain

- src/optimizer/plan_nodes/logical_aggregate.rs
- src/optimizer/plan_nodes/logical_filter.rs
- src/optimizer/plan_nodes/logical_join.rs
- src/optimizer/plan_nodes/logical_limit.rs
- src/optimizer/plan_nodes/logical_order.rs
- src/optimizer/plan_nodes/logical_projection.rs
- src/optimizer/plan_nodes/logical_table_scan.rs
- src/optimizer/plan_nodes/mod.rs
- src/optimizer/plan_nodes/physical_filter.rs
- src/optimizer/plan_nodes/physical_hash_agg.rs
- src/optimizer/plan_nodes/physical_hash_join.rs
- src/optimizer/plan_nodes/physical_limit.rs
- src/optimizer/plan_nodes/physical_nested_loop_join.rs
- src/optimizer/plan_nodes/physical_order.rs
- src/optimizer/plan_nodes/physical_projection.rs
- src/optimizer/plan_nodes/physical_simple_agg.rs
- src/optimizer/plan_nodes/physical_table_scan.rs
Signed-off-by: MingjiHan <mingji_han@outlook.com>
We may need an execution context (like DuckDB) to provide statitsics in storage layer for optimizer @skyzh .
> feat(optimizer): add cardinality trait

- README.md
Signed-off-by: Yingjun Wu <yingjunwu@singularity-data.com>
> Tweak README.md to make it more inclusive

- src/executor/delete.rs
- src/executor/drop.rs
- src/main.rs
part of https://github.com/risinglightdb/risinglight/issues/454
> cli: improve `drop` message

- Cargo.lock
- Cargo.toml
- src/array/data_chunk.rs
- src/executor/limit.rs
- src/executor/mod.rs
- src/executor/order.rs
- src/executor/top_n.rs
- src/optimizer/logical_plan_rewriter/convert_physical.rs
- src/optimizer/mod.rs
- src/optimizer/plan_nodes/logical_top_n.rs
- src/optimizer/plan_nodes/mod.rs
- src/optimizer/plan_nodes/physical_top_n.rs
- src/optimizer/rules/limit_order_rule.rs
- src/optimizer/rules/mod.rs
closes https://github.com/risinglightdb/risinglight/issues/404
also closes https://github.com/risinglightdb/risinglight/issues/444 (let limit return a dummy chunk if offset is out of bound or limit=0)
(since I tested `TopN` using `Limit`
Some example runs:
> executor: support TopN

- CONTRIBUTING.md
- GOVERNANCE.md
- README.md
related discussion: https://github.com/risinglightdb/risinglight/discussions/425
> docs: update scrum meeting and governance

- src/storage/secondary/column.rs
- src/storage/secondary/column/column_iterator.rs
- src/storage/secondary/column/concrete_column_iterator.rs
- src/storage/secondary/column/primitive_column_factory.rs
- src/storage/secondary/rowset/rowset_iterator.rs
> refactor(storage): remove filter scan functionality on column iterator

- src/storage/secondary/rowset/rowset_iterator.rs
close https://github.com/risinglightdb/risinglight/issues/483
> refactor(storage): remove unnecessary option for column_iterators item

- Cargo.lock
- Cargo.toml
- src/main.rs
Signed-off-by: tabVersion <tabvision@bupt.icu>
close: https://github.com/risinglightdb/risinglight/issues/471
> feat(cli): print query time

- build.rs
- src/storage/secondary/column/blob_column_builder.rs
Signed-off-by: arkbriar <arkbriar@gmail.com>
Fixes #463 .
> fix(storage): fix panic when finishing an empty blob builder.

- .github/workflows/ci.yml
> feat(ci): switch to nextest

- src/optimizer/plan_nodes/plan_tree_node.rs
- src/storage/secondary/statistics/statistics_builder.rs
- src/types/blob.rs
- src/utils/sync/counter.rs
- src/utils/sync/mod.rs
Signed-off-by: arkbriar <arkbriar@gmail.com>
> chore: fix docs and add license headers

- src/storage/secondary/mod.rs
Reverts risinglightdb/risinglight#497
> Revert "fix(storage): ignore errors on shutdown."

- Cargo.lock
- Cargo.toml
- src/main.rs
- tests/sqllogictest.rs
> tests: use `AsyncDB` (re #485)

- src/logical_planner/delete.rs
- tests/sql/delete.slt
Signed-off-by: alissa-tung <alissa-tung@outlook.com>
> executor: support delete full table, in terms of `delete {} where true`

- build.rs
- src/binder/table_ref/mod.rs
- src/catalog/database.rs
- src/catalog/mod.rs
- src/executor/internal.rs
- src/executor/mod.rs
- src/logical_planner/select.rs
- src/optimizer/logical_plan_rewriter/input_ref_resolver.rs
- src/optimizer/plan_nodes/internal.rs
- src/optimizer/plan_nodes/mod.rs
- tests/sql/catalog.slt
close https://github.com/risinglightdb/risinglight/issues/99
```sql
> \dt
+---+----------+---+------------+---+--------------+
| 0 | postgres | 1 | pg_catalog | 0 | contributors |
+---+----------+---+------------+---+--------------+
> select * from pg_catalog.contributors
+--------------+
| name         |
+--------------+
| Alex Chi     |
| Alissa Tung  |
| ArkBriar     |
| Chojan Shang |
| Frank Ma     |
| Lu Di        |
| Mingj        |
| MingjiHan    |
| Runji Wang   |
| Tab Zhang    |
| TennyZhuang  |
| Ting Sun     |
| Yingjun Wu   |
| Yuhui Liu    |
| Yujia Qiao   |
| Zehao Wei    |
| kutori       |
| likg227      |
| nanderstabel |
| stonepage    |
| wzl          |
| xxchan       |
| xyz          |
| 庄天翼       |
|              |
+--------------+
```
```sql
> select count(*) from …
```
> feat: internal table support (contributors)

- Cargo.lock
- Cargo.toml
Signed-off-by: alissa-tung <alissa-tung@outlook.com>
> minor fix: update `sqllogictest` pkg remote url

- src/optimizer/plan_nodes/physical_nested_loop_join.rs
- src/optimizer/plan_nodes/physical_order.rs
part of https://github.com/risinglightdb/risinglight/issues/410
> feat(executor): improve explain of OrderBy and NLJ

- .github/workflows/ci.yml
part of https://github.com/risinglightdb/risinglight/issues/519
Though I think this might be out-of-space error... I still want to try if sudo could solve this problem.
> fix(ci): frequent permission error

- src/storage/secondary/block/rle_block_iterator.rs
close #525 
Signed-off-by: ludics <leonludics@gmail.com>
> fix(storage): fix bug of RleBlockIterator.skip()

- src/binder/expression/column_ref.rs
- src/binder/expression/mod.rs
- src/binder/statement/select.rs
- src/logical_planner/mod.rs
- src/logical_planner/select.rs
- src/optimizer/logical_plan_rewriter/input_ref_resolver.rs
- src/optimizer/plan_nodes/logical_aggregate.rs
- src/optimizer/plan_nodes/logical_projection.rs
- src/optimizer/plan_nodes/physical_hash_agg.rs
- tests/sql/group_by.slt
try to close https://github.com/risinglightdb/risinglight/issues/526
> feat(executor): support group by expression

- src/executor/internal.rs
> chore: update contributors

- src/optimizer/plan_nodes/logical_filter.rs
Signed-off-by: xiejiann <jianxie0@gmail.com>
close #547 
Map the index when pruning cols in the filter
> feat: map filter inputref

- src/storage/secondary/manifest.rs
Signed-off-by: BaymaxHWY <854541526@qq.com>
fix [#553](https://github.com/risinglightdb/risinglight/issues/553)
fix #552
> fix(storage): delete RowSets when drop table

- src/storage/error.rs
- src/storage/secondary/column.rs
Signed-off-by: BaymaxHWY <854541526@qq.com>
fix: #551
> chore(storage): use get_or_try_insert_with for block cache

- src/storage/secondary/column.rs
Signed-off-by: BaymaxHWY <854541526@qq.com>
remove the `TODO(chi): handle file system errors`
> chore(storage): remove TODO comment

- src/executor/mod.rs
- src/executor/values.rs
- src/types/mod.rs
Signed-off-by: xiaoyong-z <a997647204@gmail.com>
close #455 
1. add char and varchar length check in  ValuesExecutor
> fix(executor): Char and Varchar's length limit not respected

- .github/workflows/ci.yml
- tests/sqllogictest/build.rs
- tests/sqllogictest/src/lib.rs
- tests/sqllogictest/tests/.gitignore
- tests/sqllogictest/tests/sqllogictest.rs
After https://github.com/risinglightdb/risinglight/pull/568, sqllogictest is not running on CI! This PR attempts to fix it.
> fix(ci): sqllogictest not running

- src/storage/secondary/transaction.rs
Closes: #495 
Signed-off-by: Noel Kwan <noelkwan1998@gmail.com>
> chore(storage) improve flush logging

- README.md
We've finished proposing the v0.2 roadmap in https://github.com/risinglightdb/risinglight/issues/572
> docs: update roadmap issue

- Cargo.lock
- Cargo.toml
- tests/sqllogictest/Cargo.toml
> chore: use published crates

- Cargo.lock
- Cargo.toml
- proto/Cargo.toml
- proto/README.md
I've already published risinglight_proto.
The final problem is sqlparser-rs. Shall we publish it as `risinglight_sqlparser`?
ref https://github.com/risinglightdb/risinglight/issues/574
> release: bump to v0.1.1

- src/array/mod.rs
- src/executor/evaluator.rs
Part of #464, implements solution for `ArrayImpl::Bool`
Signed-off-by: Noel Kwan [noelkwan1998@gmail.com](mailto:noelkwan1998@gmail.com)
> refactor(executor): refactor ArrayImpl::Bool for cheap cloning

- src/array/data_chunk.rs
- src/array/mod.rs
- src/executor/aggregation/sum.rs
- src/executor/copy_from_file.rs
- src/executor/copy_to_file.rs
- src/executor/evaluator.rs
- src/executor/explain.rs
- src/executor/insert.rs
- src/executor/internal.rs
- src/executor/limit.rs
- src/executor/top_n.rs
- src/executor/values.rs
- src/storage/memory/iterator.rs
- src/storage/secondary/merge_iterator.rs
- src/storage/secondary/rowset/disk_rowset.rs
- src/storage/secondary/rowset/rowset_writer.rs
close https://github.com/risinglightdb/risinglight/issues/464
ref https://github.com/risinglightdb/risinglight/pull/577
I've finished the refactor 🤪 If you have any review comments, just leave it below, thanks! cc @kwannoel
> refactor(array): cheap clone for all arrays

- src/function/abs.rs
- src/function/mod.rs
- src/lib.rs
Signed-off-by: MingjiHan <mingji_han@outlook.com>
The design refers to Databend. https://github.com/datafuselabs/databend/tree/b22144300e2adaaba81f9cda772f1e00b90176f3/common/functions
TODO: support function binding and execution in our database system.
> feat(function): add function definition

- src/array/shuffle_ext.rs
- src/storage/chunk.rs
- src/storage/secondary/merge_iterator.rs
- src/storage/secondary/rowset/rowset_iterator.rs
Closes #580 
Signed-off-by: Noel Kwan <noelkwan1998@gmail.com>
> refactor(storage): remove Arc from Arc<ArrayImpl>

- Cargo.toml
- benches/e2e.rs
- src/db.rs
- src/main.rs
- src/optimizer/logical_plan_rewriter/arith_expr_simplification.rs
- tests/sqllogictest/src/lib.rs
close https://github.com/risinglightdb/risinglight/issues/582
> feat(tracing): make minitrace  a cli option

- src/storage/secondary/column/concrete_column_iterator.rs
Hi, I am a newbie for risinglight and rust :) 
The current patch want to fix #474.
Now it simply outputs the next_batch_count in ConcreteColumnIterator drop() function.
```sh
> select sum(L_LINENUMBER) from LINEITEM;
...
2022-03-30T02:51:14.669643Z DEBUG risinglight::storage::secondary::column::concrete_column_iterator: Statistics {
next_batch_count: 195,
}
2022-03-30T02:51:14.669749Z DEBUG risinglight::storage::secondary::column::concrete_column_iterator: Statistics {
next_batch_count: 913,
}
2022-03-30T02:51:14.669763Z DEBUG risinglight::storage::secondary::column::concrete_column_iterator: Statistics {
next_batch_count: 913,
}
2022-03-30T02:51:14.669775Z DEBUG risinglight::storage::secondary::column::concrete_column_iterator: Statistics {
next_batch_count: 913,
}
```
How can I …
> feat(storage): report statistics after finishing table scan (#474)

- README.md
Now we have a standalone community!
> docs: migrate to new Slack community

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- proto/Cargo.toml
close #604
Signed-off-by: alissa-tung <alissa-tung@outlook.com>
> deps: upgrade prost 0.10

- src/executor/sort_merge_join.rs
Signed-off-by: d2lark <lichengamoy@gmail.com>
complete test case for sort-merge-join exexcutor
> chore(test): add more test case

- CONTRIBUTING.md
- README.md
- docs/00-develop.md
close https://github.com/risinglightdb/risinglight/issues/615
cc @D2Lark may also take a look, comment and approve 🤪
> docs: add instructions to install protobuf

- src/executor/values.rs
close https://github.com/risinglightdb/risinglight/issues/619
Signed-off-by: Jayice <1185430411@qq.com>
> executor: use DataChunkbuilder to refactor ValuesExecutor

- GOVERNANCE.md
- README.md
vote at https://github.com/risinglightdb/risinglight/discussions/628
> community: add xxchan as maintainer

- src/array/data_chunk_builder.rs
- src/executor/copy_from_file.rs
refactor CopyFromFile using DataChunkBuilder
close #618
> refactor(executor): refactor CopyFromFile using DataChunkBuilder

- src/binder/statement/create_table.rs
- src/binder/statement/drop.rs
- src/binder/statement/insert.rs
- src/catalog/database.rs
- src/catalog/root.rs
- src/catalog/schema.rs
- src/catalog/table.rs
- src/storage/memory/mod.rs
- src/storage/secondary/manifest.rs
> chore: remove Mutex in database/schema/table catalog

- tests/sqllogictest/tests/sqllogictest.rs
> chore(test): ensure single thread runtime for sqllogictest

- Cargo.lock
- Cargo.toml
- src/storage/secondary/column.rs
- tests/sqllogictest/Cargo.toml
This PR upgrades dependencies to fix [security alert #1](https://github.com/risinglightdb/risinglight/security/dependabot/1).
> chore: upgrade dependencies

- Cargo.lock
- Cargo.toml
- src/main.rs
- src/storage/secondary/block/rle_block_builder.rs
> chore: bump dependencies

- src/storage/secondary/block/char_block_builder.rs
Signed-off-by: lokax <m632656684@gmail.com>
> fix(storage): reserve correct size

- tests/sqllogictest/src/lib.rs
- tests/sqllogictest/tests/sqllogictest.rs
Signed-off-by: xxchan <xxchan22f@gmail.com>
> refactor: remove unnecessary current dir

- src/optimizer/plan_nodes/logical_table_scan.rs
This PR close #450.
Signed-off-by: Yue Yin <yueyin.dev@gmail.com>
> fix: add row_handler to schema

- src/storage/secondary/block.rs
- src/storage/secondary/block/blob_block_builder.rs
- src/storage/secondary/block/char_block_builder.rs
- src/storage/secondary/block/dict_block_builder.rs
- src/storage/secondary/block/primitive_block_builder.rs
- src/storage/secondary/block/primitive_nullable_block_builder.rs
- src/storage/secondary/block/rle_block_builder.rs
- src/storage/secondary/column/primitive_column_builder.rs
- src/storage/secondary/encode.rs
🤣 #670 has been completed in issue #699, so we can support dict-encoding in primitive column builder.
> feat(storage): support dict encoding in primitive column builder

- src/storage/secondary/block.rs
- src/storage/secondary/block/blob_block_builder.rs
- src/storage/secondary/block/blob_block_iterator.rs
- src/storage/secondary/block/char_block_builder.rs
- src/storage/secondary/block/char_block_iterator.rs
- src/storage/secondary/block/nullable_block_builder.rs
- src/storage/secondary/block/nullable_block_iterator.rs
- src/storage/secondary/block/primitive_block_builder.rs
- src/storage/secondary/block/primitive_block_iterator.rs
What's changed:
- Introduce generic nullable block encoding
- Support nullable encoding on blob, primitive, char
- Add new pair of traits `NonNullableBlockBuilder` & `NonNullableBlockIterator`
close #533
> feat(storage): generic nullable block encoding

- src/binder_v2/copy.rs
- src/binder_v2/create_table.rs
- src/binder_v2/delete.rs
- src/binder_v2/mod.rs
- src/binder_v2/table.rs
- src/catalog/column.rs
- src/planner/mod.rs
Signed-off-by: Elias.Yao <siran0611@gmail.com>
> feat(binder): new binder for copy, delete and create_table

- Cargo.lock
- Cargo.toml
- src/binder_v2/expr.rs
- src/types/date.rs
- src/v1/binder/expression/type_cast.rs
Signed-off-by: TennyZhuang <zty0826@gmail.com>
> build: bump deps

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- proto/Cargo.toml
- src/binder_v2/select.rs
- src/storage/secondary/manifest.rs
close https://github.com/risinglightdb/risinglight/issues/572
> release: v0.2

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- docs/03-architecture-overview.md
- readmap 0.2 done  👋
- deprecate Slack 👋
- deprecate scrum meeting 👋
- Singularity Data -> RisingWave Labs
> docs: update README

- Cargo.lock
- Cargo.toml
- src/binder_v2/create_table.rs
- src/binder_v2/drop.rs
- src/catalog/column.rs
- src/executor_v2/explain.rs
- src/main.rs
- src/planner/explain.rs
- src/utils/mod.rs
- tests/planner_test/count.planner.sql
- tests/planner_test/tpch.planner.sql
Edit: here's an example from planner tests:
```
Projection { cost: 8163.5923, exprs: [ sum {  } ] }                                                                 
└── Aggregate { aggs: [ sum {  } ], cost: 8161.992, group_by: [] }                                                  
└── Projection { cost: 7964.3843, exprs: [ l_extendedprice, l_discount ] }                                      
└── Filter                                                                                                  
├── cond: and                                                                                           
│   ├── lhs: >= { lhs: l_shipdate, rhs: 1994-01-01 }                                                    
│   └── rhs: and …
```
> feat(explain): reimplement explain using pretty-xmlish

- Cargo.lock
- tests/planner_test/tpch.planner.sql
Was introduced in #771, fix the problem mentioned in https://github.com/risinglightdb/risinglight/pull/777#issuecomment-1435994648
> feat(pretty): fix singleton lists pretty printing

- Cargo.toml
Hopefully fixing https://github.com/risinglightdb/risinglight/security/dependabot/5
> chore: fix CVE report

- src/catalog/root.rs
- src/db.rs
Signed-off-by: sandflee [sandflee.fang@gmail.com](mailto:sandflee.fang@gmail.com)
```
\d pg_catalog.contributors
+---+-----------+--------+----------+---+
| 0 | github_id | string | not null |   |
+---+-----------+--------+----------+---+
\d nation
+---+-------------+--------+----------+---+
| 0 | n_nationkey | int    | not null |   |
| 1 | n_name      | string | not null |   |
| 2 | n_regionkey | int    | not null |   |
| 3 | n_comment   | string | nullable |   |
+---+-------------+--------+----------+---+
```
> feat(command): add \d command to show table column info

- src/array/ops.rs
- src/array/utf8_array.rs
- src/binder_v2/expr.rs
- src/executor_v2/evaluator.rs
- src/planner/explain.rs
- src/planner/mod.rs
- src/planner/rules/type_.rs
- tests/sql/replace.slt
- tests/sqllogictest/tests/sqllogictest.rs
Impl #387 
Update:
- add `replace` function support
- fix `BytesArray::from_data` missing initial offset 0.
> feat: support scalar function

- Cargo.lock
- Cargo.toml
- build.rs
- docs/07-python-extension.md
- src/binder/copy.rs
- src/binder/delete.rs
- src/binder/expr.rs
- src/binder/mod.rs
- src/binder/select.rs
- src/lib.rs
- tests/planner_test/count.planner.sql
- tests/planner_test/extract-common-predicate.planner.sql
- tests/planner_test/tpch.planner.sql
Also added a new feature "python" to build pyo3.
> chore(deps): update dependencies

- docs/03-architecture-overview.md
The project code seems to have undergone a refactoring and some links are faulty. Optimizer links are also wrong, but I don't know which one to fill in, I can't find the corresponding module, it seems to go with the planner module
> (fix/doc): fix error link

- src/binder/drop.rs
- src/binder/mod.rs
> chore/binder: throw err for other objectnames

- Cargo.lock
- Cargo.toml
- src/executor/hash_agg.rs
- src/executor/hash_join.rs
- src/storage/secondary/index.rs
For tpch 10GB 's Q6 , 1:11 -> 1:05
> feat: use ahash for better hash performance

- .github/workflows/bench.yml
> fix(ci): fix benchmark workflow

- .github/workflows/bench.yml
- Makefile
no idea about the root cause so let's just chmod for now...
> fix(ci): try fix tpch permission error
