Cargo.toml, src/lib.rs
Separate jemalloc as a default feature
Resolves https://github.com/risinglightdb/risinglight/issues/275
=> feat: separate jemalloc as a feature

Cargo.lock, Cargo.toml, src/lib.rs
The original jemallocator seems not maintained actively any more. We can move to tikv-jemallocator.
=> chore: switch to tikv-jemallocator

src/array/data_chunk.rs, src/db.rs, src/executor/copy_from_file.rs, src/executor/evaluator.rs, src/executor/hash_agg.rs, src/executor/hash_join.rs, src/executor/insert.rs, src/executor/limit.rs, src/executor/mod.rs, src/executor/nested_loop_join.rs, src/executor/table_scan.rs, src/executor/values.rs, src/storage/memory/iterator.rs, src/storage/memory/table.rs, src/storage/memory/transaction.rs, src/storage/secondary/rowset/disk_rowset.rs, src/storage/secondary/rowset/rowset_builder.rs
This PR makes `CopyFromFile` and `Values` executors split chunks. (Part of #348)
=> refactor(executor): split chunks

src/array/data_chunk.rs, src/executor/hash_agg.rs, src/executor/hash_join.rs, src/executor/mod.rs, src/executor/nested_loop_join.rs, src/executor/order.rs, src/executor/simple_agg.rs, src/executor/values.rs, src/optimizer/logical_plan_rewriter/convert_physical.rs, src/storage/secondary/rowset/mem_rowset.rs
This PR refactors `NestedLoopJoin` and `HashJoin` executors, and adds outer join support to hash join.
=> feat(join): refactor and support outer join for hash join

src/executor/mod.rs, src/executor/nested_loop_join.rs, src/logical_planner/select.rs, src/optimizer/expr_utils.rs, src/optimizer/logical_plan_rewriter/convert_physical.rs, src/optimizer/plan_nodes/join_predicate.rs, src/optimizer/plan_nodes/logical_join.rs, src/optimizer/plan_nodes/mod.rs, src/optimizer/plan_nodes/physical_hash_join.rs, src/optimizer/plan_nodes/physical_nested_loop_join.rs, src/optimizer/rules/filter_join_rule.rs
- refactor join predicate 
- fix hash join determine 
- inner join predicate push down 
- fix a bug in `NestedLoopJoinExecutor`
And after that, our TPC-H Q3 is optimal with HashJoin
```
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| PhysicalLimit: offset: 0, limit: 10                                                                                                                       |
|   PhysicalOrder: [InputRef #1 (desc), InputRef #2 (asc)]                                                                                                  |
|     PhysicalProjection: exprs [InputRef #0, InputRef #3 (alias to revenue), InputRef #1, InputRef #2] …
```
=> feat(optimizer): join predicate 

src/binder/expression/mod.rs, src/storage/secondary/encode.rs, src/types/date.rs, src/types/interval.rs, tests/sql/tpch/q10.slt, tests/sql/tpch/q5.slt, tests/sql/tpch/tpch.slt, tests/sqllogictest.rs
This PR adds TPC-H Q5 and fixes `date + interval (month)` to pass TPC-H Q10.
=> feat: support TPC-H Q5 & Q10

Cargo.lock, Cargo.toml, docs/00-develop.md, src/db.rs, src/lib.rs, src/main.rs, src/storage/memory/transaction.rs, src/storage/secondary/compactor.rs, src/storage/secondary/manifest.rs, src/storage/secondary/mod.rs, src/storage/secondary/options.rs, src/storage/secondary/storage.rs, src/storage/secondary/transaction.rs, src/storage/secondary/version_manager.rs
part of https://github.com/risinglightdb/risinglight/issues/368
Also, the default log level is changed to INFO.
By the way, it seems that `EnvFilter` doesn't implement `Filter`, and therefore we cannot use per-layer filtering implemented in https://github.com/tokio-rs/tracing/pull/1523. This would lead to problems with integrating with tokio-console's Tokio-runtime tracing: if we enable tokio-runtime's tracing feature, all tokio tracing logs will be printed in stdout. We will fix this when the upstream implements `Filter` for `EnvFilter`.
=> feat: switch to tracing ecosystem

src/storage/memory/table.rs, src/storage/mod.rs, src/storage/secondary/table.rs
part of https://github.com/risinglightdb/risinglight/issues/389
Issue Number: close https://github.com/risinglightdb/risinglight/issues/393
Signed-off-by: tabVersion tabvision@bupt.icu
--- 
one question: 
Since `ReadResultFuture`, `WriteResultFuture` and `UpdateResultFuture` share type `Future<Output = StorageResult<Self::TransactionType>>`, why rust requires implementing them separately.
=> refactor(table): remove async_trait for Table trait

build.rs, src/array/data_chunk.rs, src/array/mod.rs, src/array/utf8_array.rs, src/binder/expression/mod.rs, src/binder/expression/type_cast.rs, src/executor/evaluator.rs, src/executor/filter.rs, src/executor/hash_agg.rs, src/executor/nested_loop_join.rs, src/executor/projection.rs, src/executor/simple_agg.rs, src/executor/values.rs, src/optimizer/logical_plan_rewriter/constant_folding.rs, src/types/blob.rs, src/types/date.rs, src/types/mod.rs, tests/sql/blob.slt
This PR adds initial support for blob type.
We borrowed a test script from DuckDB and managed to pass most of the tests on memory storage.
The failed case is `SELECT NULL::BLOB`, which needs further fixes in our binder.
This PR also proposes another approach to support unsized types in array without using GAT (related discussion #381).
In short, we can define unsized types over a slice, like `std::path::Path`. They have the same memory layout as `[u8]` but can parse the underlying data in their own way. For more details, you can see `BlobRef` in the code.
TODO: support blob type on disk storage.
=> feat: add initial support for blob type

src/array/data_chunk.rs, tests/sql/issue-398.slt
Try to close https://github.com/risinglightdb/risinglight/issues/398
This table creation syntax is not standard and weird but supported by PostgreSQL. like this:
```
postgres@127:db1> create table t();
CREATE TABLE
Time: 0.006s
postgres@127:db1> select * from t;
SELECT 0
Time: 0.002s
```
After investigation, I found sqlparser-rs also supported this syntax, see https://github.com/sqlparser-rs/sqlparser-rs/pull/94. so RisingLight could parse successfully.
I think RisingLight should support the query `no columns table` instead of throwing exception on table creation.
So I just fixed the code that caused panic to avoid process termination.
=> fix(array): support no columns table

Makefile
1. Use `mkdir -p {}` instead of `mkdir {} || true`. `mkdir` may failed due to other reasons, e.g. no disk space or permission error or `target` already exists with a file but not a directory.
2. also clean tpch dir in `make clean`
Signed-off-by: TennyZhuang <zty0826@gmail.com>
=> chore: refine Makefile clean

src/optimizer/mod.rs, src/optimizer/plan_nodes/logical_explain.rs, src/optimizer/plan_nodes/mod.rs
add `prune_col` method on `PlanNode`, every logical node should implement `fn prune_col(&self, required_cols: BitSet) -> PlanRef`, which will optimize itself and output only the required columns. Now there is a default implementation which is insert a `LogialProjection` on the top of the Node.
ref https://github.com/risinglightdb/risinglight/issues/388
=> feat(optimizer): column pruning framework

src/storage/error.rs
Previously:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TracedStorageError { source: JsonDecode(Error("missing field `name`", line: 1, column: 233)), backtrace: Backtrace [{ fn: "std::backtrace_rs::backtrace::libunwind::trace", file: "/rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/../../backtrace/src/backtrace/libunwind.rs", line: 93 }, { fn: "std::backtrace_rs::backtrace::trace_unsynchronized", file: "/rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/../../backtrace/src/backtrace/mod.rs", line: 66 }, { fn: "std::backtrace::Backtrace::create", file: "/rustc/5e57faa78aa7661c6000204591558f6665f11abc/library/std/src/backtrace.rs", line: 328 }, { fn: …
```
=> chore(storage): fix error display

src/executor/hash_join.rs, src/executor/nested_loop_join.rs
Instead of waiting until left side completes, the children executors can be driven concurrently to improve cpu utilization.
Experiments on my mac shows significant improvement on response time of queries with joins. 
`join`
```bash
hyperfine --warmup 3 './target/release/risinglight -f tests/sql/tpch/q1.sql'
Benchmark 1: ./target/release/risinglight -f tests/sql/tpch/q1.sql
Time (mean ± σ):      3.901 s ±  0.054 s    [User: 5.423 s, System: 0.694 s]
Range (min … max):    3.865 s …  4.040 s    10 runs
hyperfine --warmup 3 './target/release/risinglight -f tests/sql/tpch/q3.sql'
Benchmark 1: ./target/release/risinglight -f tests/sql/tpch/q3.sql
Time (mean ± σ):      1.353 s ±  0.020 s    [User: 1.341 s, System: 0.448 s]
Range (min … max):    1.329 s …  1.396 s    10 runs
hyperfine --warmup 3 …
```
=> refactor(executor): poll concurrently with tokio::try_join! in join executors.

src/storage/secondary/column.rs, src/storage/secondary/column/column_iterator.rs, src/storage/secondary/column/concrete_column_iterator.rs, src/storage/secondary/rowset/rowset_iterator.rs
=> refactor(storage): merge next_batch_inner and next_batch_inner_with_filter in rowset_iterator

src/storage/secondary/column/concrete_column_iterator.rs, src/storage/secondary/column/primitive_column_factory.rs
Follow-up of #424 
For [the optimization](https://github.com/risinglightdb/risinglight/pull/424#discussion_r802473971), I think we already ensured `self.dvs` not to be empty at L137, right? cc @skyzh
https://github.com/risinglightdb/risinglight/blob/1a026b6ff74c57b27688c904094f145861931bf4/src/storage/secondary/rowset/rowset_iterator.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L135-L153
=> chore(storage): remove redundant get_current_row_id

src/db.rs
=> cli: trim command's leading and trailing whitespace

src/array/data_chunk.rs, src/executor/hash_join.rs, src/executor/mod.rs, src/optimizer/logical_plan_rewriter/convert_physical.rs, src/optimizer/plan_nodes/join_predicate.rs, src/optimizer/plan_nodes/physical_hash_join.rs, tests/sql/join.slt
closes https://github.com/risinglightdb/risinglight/issues/362
- `PhysicalHashJoin`'s `left/right_column_index` fields are deleted, only `logical` left. 
- `HashJoinExecutor`'s same fields are changed from `index` -> `indexes`. They are computed in `visit_physical_hash_join` now. (Previously in `rewrite_logical_join`)
=> executor: hash join support multi columns as hash key.

src/array/data_chunk.rs, src/executor/create.rs, src/optimizer/plan_nodes/logical_create_table.rs, src/optimizer/plan_nodes/physical_create_table.rs
part of https://github.com/risinglightdb/risinglight/issues/442
=> refactor(executor): use plan node to infer column name

src/storage/secondary/mod.rs
Signed-off-by: arkbriar <arkbriar@gmail.com>
Shutdown of secondary storage might panic when the whole runtime's shutting down. 
It's ok to ignore the errors here.
```bash
---- disk::_blob_slt_ stdout ----
thread 'tokio-runtime-worker' panicked at 'empty rowset', src/storage/secondary/rowset/rowset_builder.rs:104:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'disk::_blob_slt_' panicked at 'called `Result::unwrap()` on an `Err` value: ()', .../risinglight/src/storage/secondary/mod.rs:142:44
```
=> fix(storage): ignore errors on shutdown.

src/binder/expression/mod.rs, src/logical_planner/select.rs, tests/sql/count.slt
fix https://github.com/risinglightdb/risinglight/issues/501
```sql
> explain select count(*) from t;
PhysicalProjection: exprs [InputRef #0]
PhysicalSimpleAgg: 1 agg calls
PhysicalTableScan: table #10, columns [], with_row_handler: true, is_sorted: false, expr: None
> explain select 1 from t;
PhysicalProjection: exprs [Int32(1) (const)]
PhysicalTableScan: table #10, columns [], with_row_handler: false, is_sorted: false, expr: None
> explain select count(*)+1 from t;
PhysicalProjection: exprs [Plus(InputRef #0, Int32(1) (const))]
PhysicalSimpleAgg: 1 agg calls
PhysicalTableScan: table #10, columns [], with_row_handler: true, is_sorted: false, expr: None
> explain select -count(*) from t;
PhysicalProjection: exprs [BoundUnaryOp { op: Minus, expr: InputRef #0, return_type: Some(Int(None)) }] …
```
=> fix(planner): row handler not included when count(*) is used as subexpression

src/storage/mod.rs, src/storage/secondary/rowset/rowset_iterator.rs
If `filter_map` is all false when filter condition gets evaluated, as we have already scanned filter columns, we should not skip them.
=> fix(storage): filter columns will be skipped incorrectly

src/executor/limit.rs, tests/sql/limit.slt
Fix https://github.com/risinglightdb/risinglight/issues/264
The issue can be reproduced using memory engine like this: (Btw, the sqlogictest fails for both disk & memory engines)
```sql
> create table t(x int);insert into t values (0);insert into t values (0);
> select * from t limit 0;
```
The execution process is 
```
processed 0, cardinality 1, offsef 0, limit 0
processed 1, cardinality 1, offsef 0, limit 0 # boom
```
Because when `offset=limit=0`, `start=end=0`, and thus it will `continue`.
https://github.com/risinglightdb/risinglight/blob/fea5e0b3de264e3f2275d1ca6c04c2c97ef8d639/src/executor/limit.rs#L27-L32
=> fix(executor): limit should exit early when offset and limit are both 0

src/main.rs, src/utils/time/duration.rs, src/utils/time/mod.rs
Signed-off-by: arkbriar <arkbriar@gmail.com>
close #510 
Optimize the time format to be similar to [pgcli](https://github.com/dbcli/pgcli), which prints the execution time in seconds with three precision numbers and also a human-readable duration in seconds when the duration is longer than 1 second.
Examples: 
1. Empty lines (no output)
```bash
> 
> 
> 
```
2. In 1s (only duration in seconds)
```bash
select count(*) from lineitem;
+---------+
| count   |
+---------+
| 6001215 |
+---------+
in 0.186s
```
3. Longer than 1s (with human-readable duration)
```bash
select
l_returnflag,
l_linestatus,
sum(l_quantity) as sum_qty,
sum(l_extendedprice) as sum_base_price,
sum(l_extendedprice * (1 - l_discount)) as sum_disc_price,
sum(l_extendedprice * (1 - l_discount) * (1 + l_tax)) as sum_charge, …
```
=> optimize(cli): optimize the execution time format and omit to print time on empty query

src/storage/secondary/options.rs
Previously, the block cache is too small. At the same time, the block size is a somehow too large that filter scan barely takes effect in TPC-H queries.
=> chore(storage): larger cache and smaller block size

Cargo.toml, src/storage/secondary/mod.rs, src/storage/secondary/table.rs, src/storage/secondary/transaction.rs, src/storage/secondary/transaction_manager.rs
It turned out that tokio already has an `OwnedMutexGuard`... Before realizing tokio already provides such functionality, I wasted ~1hr implementing a self-referential struct and wrapping MutexGuard with a Arc by myself 🤣
=> chore(storage): use tokio OwnedMutexGuard

.gitignore, src/binder/expr_visitor.rs, src/binder/expression/mod.rs, src/binder/mod.rs, src/optimizer/logical_plan_rewriter/arith_expr_simplification.rs, src/optimizer/logical_plan_rewriter/bool_expr_simplification.rs, src/optimizer/logical_plan_rewriter/constant_folding.rs, src/optimizer/logical_plan_rewriter/constant_moving.rs, src/optimizer/logical_plan_rewriter/input_ref_resolver.rs, src/optimizer/logical_plan_rewriter/mod.rs, src/optimizer/plan_nodes/logical_filter.rs, src/optimizer/plan_nodes/logical_projection.rs, src/optimizer/plan_nodes/logical_table_scan.rs
- Introduce `ExprVisitor`, `ExprRewriter` (aka `ExprVisitorMut`?) to reduce duplicated traversing code. 
> Yes, we are implementing too many things on `BoundExpr`... Maybe we can implement some visitors for expr :)
>
> _Originally posted by @skyzh in https://github.com/risinglightdb/risinglight/issues/535#issuecomment-1055151048_
- Optimizer: Add a rule to merge nested projection & Implement `prune_col` for filter (which used the visitor)
=> refactor: introduce visitor for expr

src/array/data_chunk.rs, src/db.rs, src/executor/delete.rs, src/executor/drop.rs, src/executor/explain.rs, src/executor/insert.rs, src/optimizer/plan_nodes/logical_delete.rs, src/optimizer/plan_nodes/logical_drop.rs, src/optimizer/plan_nodes/logical_explain.rs, src/optimizer/plan_nodes/logical_insert.rs
Signed-off-by: RinChanNOWWW <hzy427@gmail.com>
close https://github.com/risinglightdb/risinglight/issues/435
Remove the member `header` in the struct `DataChunk`. And it seems that there is no need to add a wrapper struct `ResultChunk`. Adding `ResultChunk` will complicate the executors.
=> chore: remove header in `DataChunk`.

benches/e2e.rs, src/db.rs, src/main.rs, src/optimizer/logical_plan_rewriter/arith_expr_simplification.rs, src/storage/secondary/manifest.rs, src/storage/secondary/storage.rs, tests/sqllogictest/src/lib.rs
TL;DR, the db interface itself should not expose `enable_tracing`. Tracing is enabled automatically if there's a parent tracing span in current thread.
Also remove fsync from manifest if is in-memory backend. 2x faster for storage e2e tests.
ref https://github.com/risinglightdb/risinglight/pull/586
=> chore(tracing): remove enable_tracing option from db interface

Cargo.lock, Cargo.toml
Our patch for sqlparser-rs has been upstreamed: https://github.com/sqlparser-rs/sqlparser-rs/pull/446.
No more blockers to publishing RisingLight! #574
=> chore: switch sqlparser-rs to crates.io version

.github/workflows/bench.yml, .github/workflows/ci.yml
Directly downloading from protoc pre-built binary could be a little bit faster 🤪 Also, we download protoc compiler in bench workflow.
=> chore(ci): install protoc by direct download

src/storage/secondary/compactor.rs, src/storage/secondary/merge_iterator.rs, src/storage/secondary/transaction.rs
Signed-off-by: BaymaxHWY <854541526@qq.com>
close issue: [#588 ](https://github.com/risinglightdb/risinglight/issues/588)
=> feat(storage): add support composite sort key in MergeIterator

src/logical_planner/select.rs, src/optimizer/logical_plan_rewriter/input_ref_resolver.rs, tests/sql/group_by.slt
fix part of https://github.com/risinglightdb/risinglight/issues/539
the original group by expression support (https://github.com/risinglightdb/risinglight/pull/535) seems not very clear for resolving `InputRef`, so I refactor the main logic to `InputRefResolver`. And fix panic for:
```sql 
select v2 + 1 + count(*) from t group by v2 + 1;
```
but it still leaves some issues:
- panic `select v2 + 2 + count(*) from t group by v2 + 1;`
=> refactor(planner): use AggInputRefResolver to handle group by expr

src/binder/statement/create_table.rs, src/catalog/table.rs, tests/sql/filter.slt
Signed-off-by: Shmiwy <wyf000219@126.com>
#625 1st editon
support primary key (a, b) syntax by adding a field called `primary_key_ids` in `TableCatalog` without removng `is_primary field` from `ColumnDesc`. I will remove `is_primary` and refactor code when I want to extend the case to multiple sort keys.
=> feat(binder): support `primary key (a, b)` syntax

src/binder/statement/create_table.rs, src/binder/statement/drop.rs, src/binder/statement/insert.rs, src/catalog/database.rs, src/catalog/schema.rs, src/catalog/table.rs, src/db.rs, src/executor/create.rs, src/executor/insert.rs, src/logical_planner/create.rs, src/optimizer/plan_nodes/logical_create_table.rs, src/storage/memory/mod.rs, src/storage/mod.rs, src/storage/secondary/manifest.rs, src/storage/secondary/mod.rs
Signed-off-by: Shmiwy <wyf000219@126.com>
try to implementation #625
at this moment, I just append `ordered_pk_ids` to `tableCatalog` withoud using  `is_primary` filed in `ColumnDesc`. It will make removing  `is_primary` in the future easier.
=> feat: support multi ordered primary key

src/logical_planner/select.rs, tests/sql/group_by.slt
fix part of https://github.com/risinglightdb/risinglight/issues/539
including two enhanced validation for `groupby` illegal columns:
- `select v2 + 2 + count(*) from t group by v2 + 1;`
- `select v2 + count(*) from t group by v2 order by v1;`
=> fix(planner): enhance group by illegal column validation

src/executor/table_scan.rs, src/storage/memory/transaction.rs, src/storage/mod.rs, src/storage/secondary/compactor.rs, src/storage/secondary/rowset/disk_rowset.rs, src/storage/secondary/rowset/rowset_iterator.rs, src/storage/secondary/transaction.rs
Signed-off-by: Shmiwy <wyf000219@126.com>
close #589
for now only support range-filter scan by first column and this column should by primary key
=> feat(storage): support range-filter scan by sort key

src/optimizer/mod.rs, src/optimizer/rules/filter_agg_rule.rs, src/optimizer/rules/mod.rs
Signed-off-by: lokax <m632656684@gmail.com>
**Support push the filter down below the agg**
**Before:**
```text
> explain select count(x), y + 1 from test group by y + 1 having count(x) > 1 and y + 1 = 2;
PhysicalProjection:
InputRef #1
InputRef #0
PhysicalFilter: expr And(Gt(InputRef #1, Int32(1) (const)), Eq(InputRef #0, Int32(2) (const)))
PhysicalHashAgg:
(InputRef #1 + 1)
count(InputRef #0) -> INT
PhysicalTableScan:
table #13,
columns [0, 1],
with_row_handler: false,
is_sorted: false,
expr: None
``` 
**After:**
```text
> explain select count(x), y + 1 from test group by y + 1 having count(x) > 1 and y + 1 = 2;
PhysicalProjection:
InputRef #1
InputRef #0
PhysicalFilter: expr Gt(InputRef #1, Int32(1) (const))
PhysicalHashAgg:
(InputRef #1 + 1)
count(InputRef #0) -> INT
PhysicalTableScan: …
```
=> feat(optimizer): push the filter down below the agg

src/binder/statement/create_table.rs, src/catalog/column.rs
This is my first pr to this repo 😁，If there are something i miss plz fell free to tell me.
close #632
=> binder: primary key should by-default be non-null

src/executor/mod.rs, src/executor/sort_agg.rs
=> feat: support sort agg

CONTRIBUTING.md, Cargo.lock, Cargo.toml, Makefile, docs/05-e2e-tests.md, src/storage/error.rs, src/storage/secondary/delete_vector.rs, src/storage/secondary/manifest.rs, src/storage/secondary/options.rs, src/storage/secondary/storage.rs, src/storage/secondary/transaction.rs, src/storage/secondary/version_manager.rs, tests/planner_test/count.planner.sql, tests/planner_test/count.yml, tests/planner_test/tpch.planner.sql, tests/planner_test/tpch.yml, tests/sqllogictest/src/lib.rs, tests/sqlplannertest/Cargo.toml, tests/sqlplannertest/src/bin/apply-planner-test.rs, tests/sqlplannertest/src/lib.rs, tests/sqlplannertest/tests/plannertest.rs
As title. It's a really big change :)
Basically, we will need to run `make apply_planner_test` and add the latest planner test result into the git repo.
This PR also fixes some issues about disk I/O in in-memory mode. https://github.com/risinglightdb/risinglight/issues/660 should further fix this.
=> feat(test): add sqlplannertest

src/main.rs
Signed-off-by: Gun9niR <gun9nir.guo@gmail.com>
https://github.com/risinglightdb/risinglight/issues/475
`;` at the end of a line terminates input for the current statement(s).
=> feat(cli): support multi-line interactive mode

src/main.rs
Signed-off-by: cadl <ctrlaltdeleteliu@gmail.com>
After #662, the internal command does not work. Make some fixes.
before:
```
> \dt
? ;
Internal error: unsupported command
> \dt;
Internal error: unsupported command
>
```
after:
```
> \dt
+---+----------+---+------------+---+--------------+
| 0 | postgres | 1 | pg_catalog | 0 | contributors |
+---+----------+---+------------+---+--------------+
in 0.001s
> select * from foo;
bind error: invalid table foo
> select *
? from foo;
bind error: invalid table foo
```
=> fix: 'unsupported command' everywhere

src/storage/secondary/block/rle_block_builder.rs, src/storage/secondary/block/rle_block_iterator.rs
Signed-off-by: xinchengforgit 2419743144@qq.com
This PR try to solve #531.
I have some basic thoughts about variable size encoding, but there are some tests that I don't know how to modify, please give me some suggestions.
I use variable size encoding, and replace the u16 with u32, so that we can support a larger range number while saving the used space.
=> feat(storage): use variable size encoding to compress rle count

src/binder/statement/create_table.rs
CreateTable's statement should raise an error, when its constraints contain invalid primary keys.
=> fix: create table with invalid primary keys constraints

src/binder/statement/insert.rs
close #669 
Signed-off-by: gogim1 <294843472@qq.com>
=> fix: append NULLs when inserting value with incomplete columns

src/storage/secondary/compactor.rs, src/storage/secondary/manifest.rs, src/storage/secondary/transaction.rs, src/storage/secondary/version_manager.rs
Signed-off-by: chaixuqing [xuqingchai00@gmail.com](mailto:xuqingchai00@gmail.com)
close https://github.com/risinglightdb/risinglight/issues/537
Currently, we use `pin` and `unpin` manually in code. In this request, we use `Arc<Version>` to help us automatically unpin instead of manual code.
=> storage: use Arc<Version> during pin and unpin

src/storage/secondary/compactor.rs, src/storage/secondary/rowset/disk_rowset.rs
Signed-off-by: chaixuqing [xuqingchai00@gmail.com](mailto:xuqingchai00@gmail.com)
close https://github.com/risinglightdb/risinglight/issues/638
If we find distinct value statistics is very small compared with row counts, we can use RLE encoding when building RowSets.
=>  chore(storage): select compaction strategy using statistics

src/executor/mod.rs, src/executor/perfect_hash_agg.rs
Allocate a fixed size array and use the grouping keys as an index. It doesn't calculate hash values and doesn't have hash collisions.
This PR just implemets the executor.  When we have pre-aggregated data like `min-value, max-value` as zonemap or some statistics calculated by the optimizer, we can calculate the range of values and decide whether to generate perfect hash aggregate or not.
=> feat(executor): support perfect hash aggregate

Cargo.lock, Cargo.toml, src/array/data_chunk.rs, src/array/mod.rs, src/array/primitive_array.rs, src/array/primitive_array/simd.rs, src/array/utf8_array.rs, src/binder/expression/mod.rs, src/catalog/mod.rs, src/executor/aggregation/min_max.rs, src/executor/aggregation/sum.rs, src/executor/evaluator.rs, src/function/abs.rs, src/optimizer/logical_plan_rewriter/arith_expr_simplification.rs, src/storage/secondary/column/primitive_column_builder.rs, src/storage/secondary/column/primitive_column_factory.rs, src/storage/secondary/encode.rs, src/types/blob.rs, src/types/date.rs, src/types/interval.rs, src/types/mod.rs, src/types/native.rs
This PR introduces ordered float to replace the native f32 & f64, which allows us to derive `Eq`, `Ord` and `Hash` for various types. resolve #670.
BTW, I'm attempting to integrate [egg](https://egraphs-good.github.io/) as our optimization framework. The ordered float seems to be a blocker to it.
=> feat: introduce ordered float

src/array/mod.rs, src/binder_v2/expr.rs, src/binder_v2/mod.rs, src/binder_v2/select.rs, src/binder_v2/table.rs, src/catalog/mod.rs, src/db.rs, src/executor/evaluator.rs, src/lib.rs, src/main.rs, src/planner/cost.rs, src/planner/mod.rs, src/planner/rules/mod.rs, src/planner/rules/plan.rs, src/types/mod.rs
This PR forks the current binder and integrates it with the egg language introduced by #702.
(only queries for now, other statements are left to future PR)
Now the new planner is partially connected to the pipeline: 
SQL ==parser=> Parser AST ==binder=> Egg AST ==optimizer=> Optimized Egg AST.
You can try it by first typing `\v2` and then running queries in the interactive shell:
```sql
$ cargo run
> \v2
switched to planner v2
in 0.000s
> select
l_orderkey,
sum(l_extendedprice * (1 - l_discount)) as revenue,
o_orderdate,
o_shippriority
from
customer,
orders,
lineitem
where
c_mktsegment = 'BUILDING'
and c_custkey = o_custkey
and l_orderkey = o_orderkey
and o_orderdate < date '1995-03-15'
and l_shipdate > date '1995-03-15'
group by
l_orderkey,
o_orderdate,
o_shippriority
order by
revenue …
```
=> feat(binder): introduce egg binder for queries 

src/storage/secondary/block.rs, src/storage/secondary/block/block_index_builder.rs, src/storage/secondary/column.rs
What's changed:
- Split the encode of `BlockHeader` to checksum and non-checksum
- Take non-checksum part of header (currently BlockType) to checksum calculation
- Move `BlockHeader` to the footer of block
- Change checksum validation logic
close #247 
Signed-off-by: unconsolable <chenzhipeng2012@gmail.com>
=> fix(storage): checksum BlockType in block header

src/binder_v2/select.rs, src/planner/mod.rs, src/planner/rules/agg.rs, src/planner/rules/mod.rs, src/planner/rules/plan.rs, src/planner/rules/schema.rs
This PR adds `SELECT DISTINCT (ON)` support to the new planner and fixes 2 bugs in aggregation planning.
It introduces a new plan `distinct` that uniquifies rows on the given expressions. This plan will be rewritten to `agg` by a rule. See https://github.com/risingwavelabs/risingwave/issues/4617 for details.
=> feat(planner): support `distinct on`

src/binder_v2/drop.rs, src/binder_v2/mod.rs, src/catalog/mod.rs, src/planner/mod.rs
=> feat(binder): egg binder for drop statement

src/array/mod.rs, src/binder/expression/agg_call.rs, src/binder/expression/binary_op.rs, src/binder/expression/mod.rs, src/binder/expression/unary_op.rs, src/binder/statement/insert.rs, src/executor/evaluator.rs, src/executor/hash_agg.rs, src/executor/perfect_hash_agg.rs, src/executor/simple_agg.rs, src/executor/sort_agg.rs, src/logical_planner/select.rs, src/optimizer/expr_utils.rs, src/optimizer/logical_plan_rewriter/input_ref_resolver.rs, src/optimizer/plan_nodes/join_predicate.rs, src/optimizer/plan_nodes/logical_aggregate.rs, src/optimizer/plan_nodes/logical_filter.rs, src/optimizer/plan_nodes/logical_projection.rs, src/optimizer/plan_nodes/logical_values.rs, src/optimizer/rules/filter_join_rule.rs, src/planner/rules/mod.rs, src/planner/rules/type_.rs, src/storage/secondary/column/column_builder.rs, src/storage/secondary/column/column_iterator.rs, src/storage/secondary/rowset/rowset_iterator.rs, src/types/mod.rs
This PR adds a NULL variant to the `DataTypeKind` enum, as the type of NULL value. And fixes the remaining failed tests in type analysis.
=> fix(type): add NULL type and fix type analysis

src/binder_v2/mod.rs, src/db.rs, src/lib.rs, src/planner/explain.rs, src/planner/mod.rs
@skyzh Sorry for racing with your #714. I was debugging the cost function and needed this feature to see what the hell was going on with my planner. 🤣
This PR adds the explain format to the new planner. It prints the plan in a prettier format than the original Lisp-style bracket expressions. In addition, it can print the cost of each plan if given.
```
> \v2
switched to planner v2
in 0.000s
> select
l_orderkey,
sum(l_extendedprice * (1 - l_discount)) as revenue,
o_orderdate,
o_shippriority
from
customer,
orders,
lineitem
where
c_mktsegment = 'BUILDING'
and c_custkey = o_custkey
and l_orderkey = o_orderkey
and o_orderdate < date '1995-03-15'
and l_shipdate > date '1995-03-15'
group by
l_orderkey,
o_orderdate,
o_shippriority
order by
revenue desc,
o_orderdate
limit 10;
bind:
TopN: limit=10, …
```
=> feat(planner_v2): support explain

src/binder_v2/mod.rs, src/db.rs, src/executor_v2/evaluator.rs, src/executor_v2/explain.rs, src/executor_v2/filter.rs, src/executor_v2/mod.rs, src/executor_v2/projection.rs, src/executor_v2/table_scan.rs, src/lib.rs, src/planner/mod.rs, src/planner/rules/mod.rs, src/planner/rules/schema.rs, src/planner/rules/type_.rs
This PR starts migrating executors to the new planner. The new version is put into a new module `executor_v2`. This PR finishes the migration of **scan, projection, filter, and explain** executor. Now the new planner is able to work from end to end!
```sql
> \v2
switched to planner v2
in 0.000s
> select * from nation where N_NATIONKEY = 24;
+----+---------------+---+----------------------------------------------------------------------------------------------------------------+
| 24 | UNITED STATES | 1 | y final packages. slow foxes cajole quickly. quickly silent platelets breach ironic accounts. unusual pinto be |
+----+---------------+---+----------------------------------------------------------------------------------------------------------------+
in 0.067s
> explain select * from …
```
=> feat: introduce executor v2 for the new planner

src/storage/secondary/merge_iterator.rs
Fix issue #696 
Signed-off-by: Yue Yin <yueyin.dev@gmail.com>
=> fix(storage): compaction type error

src/main.rs
Signed-off-by: MingjiHan <mjhan@bu.edu>
Add `storage_path` option so users can specify the folder of database files.  
#746
=> storage: add path option

src/planner/cost.rs, src/planner/explain.rs, src/planner/mod.rs, src/planner/rules/mod.rs, src/planner/rules/plan.rs, src/planner/rules/rows.rs, src/planner/rules/schema.rs, tests/planner_test/tpch.planner.sql
This PR upgrades **column pruning** to **projection pushdown**. Additional projections will be inserted to the plan tree, so that columns can be pruned in time after their last use.
The implementation of projection pushdown is similar to the original column pruning. Instead of generating and pushdown the `prune` node, now we directly generate the projection node with the used columns as projection. Then identical projections will be removed by the `identical-proj` rule.
Here is the execution plan of TPC-H Q10 before and after enabling projection pushdown:
```diff
Projection: [c_custkey, c_name, sum((l_extendedprice * (1 - l_discount))), c_acctbal, n_name, c_address, c_phone, c_comment]
TopN: limit=20, offset=0, …
```
=> feat(optimizer): upgrade column pruning to projection pushdown

Cargo.lock, Cargo.toml, src/lib.rs, src/main.rs, src/server/mod.rs, src/server/processor.rs
This PR adds simple support for Postgres wire protocol.
For example:
First run risinglight with command line argument `--server`:
```bash
cargo run -- --server --host localhost --port 1234
```
Then connect it with psql:
```bash
psql -h localhost -p 1234 
```
And run a few sql statements:
```bash
vpt=> insert into t03 values(1,'a');
OK
vpt=> insert into t03 values(2,'b');
OK
vpt=> insert into t03 values(3,'c');
OK
vpt=> select * from t03;
++ | ++
----+----
1  | a
2  | b
3  | c
(3 rows)
vpt=> select id from t03;
++
----
1
2
3
(3 rows)
vpt=> select a from t03;
ERROR:  bind error: invalid column a  
```
=> feat(api):support Postgres wire protocol

src/executor_v2/hash_join.rs, src/executor_v2/mod.rs, src/lib.rs, tests/planner_test/tpch.planner.sql
Generate hash join code in the compilation time to avoid testing join types during the execution for **every row**.
=> executor: use const generics to optimize hash join 

src/array/ops.rs, tests/sql/stringconcat.slt, tests/sqllogictest/tests/sqllogictest.rs
The implementation of `stringconcat` hasn't been completed. It will raise error `execute error: conversion error: no function ||(Utf8, Utf8)`, which needs to add `concat` function in `binary_op`.
Also, could I ask the reason of `O::Item: Sized` limit in `binary_op`? Could I remove it?
=> fix: complete the implementaion of `stringconcat`

src/binder_v2/expr.rs, src/binder_v2/mod.rs, src/binder_v2/select.rs, src/executor_v2/evaluator.rs, src/executor_v2/mod.rs, src/executor_v2/window.rs, src/planner/explain.rs, src/planner/mod.rs, src/planner/rules/agg.rs, src/planner/rules/mod.rs, src/planner/rules/schema.rs, src/planner/rules/type_.rs, tests/sql/window_function.slt, tests/sqllogictest/tests/sqllogictest.rs
This PR adds basic support for window functions. Available functions include `row_number` and all existing aggregate functions. Only default window (`over ()`) is supported now.
Currently the `row_number` function shares the evaluation logic with aggregations. Next step we will specialize the evaluation for window functions.
=> feat: support simple window functions

src/array/ops.rs, src/binder/expr.rs, src/executor/evaluator.rs, src/planner/explain.rs, src/planner/mod.rs, src/planner/rules/type_.rs, src/types/mod.rs, tests/sql/substring.slt
This function is used in TPC-H Q22.
We borrow the sqllogictest from duckdb and pass the common cases.
Null literal inputs are not supported yet. We may add implicit type cast in binder later.
=> feat(expr): support `substring` function

src/array/ops.rs, src/planner/rules/expr.rs, tests/sql/nullable_operator.slt
modify `binary_op` so that op(`F`) only maps to non-empty array items, else `Default::default()`.
add `binary_lop`(binary logic operator), renamed from original `binary_op`
Actually I don't quite understand the vectorization here... I just found that doing it this way prevents the bug mentioned in the issue. Maybe it's wrong to zip like this, or lose the ability to auto-vectorize?
Thanks if anyone can review it.
fix #773.
=> fix: avoid div by zero error when vectorization

docs/03-architecture-overview.md, src/catalog/root.rs
=> chore/catalog: add root test and fix doc

src/binder/drop.rs
https://github.com/risinglightdb/risinglight/pull/809
=> binder/chore: remove drop test

src/binder/expr.rs, tests/sql/basic_test.slt
I feel like it’s very simple whether timestamp will support it. There may be some problems that I didn’t pay attention to.
=> feat(type): support type-string for timestamp type

src/catalog/column.rs, src/storage/memory/table.rs, src/storage/memory/transaction.rs, src/storage/mod.rs, src/storage/secondary/compactor.rs, src/storage/secondary/manifest.rs, src/storage/secondary/rowset/mem_rowset.rs, src/storage/secondary/table.rs, src/storage/secondary/transaction.rs
Aims to solve #384, #385.
Still need to handle composite primary keys in `BTreeMapMemTable`, submitting for early feedback as there may be some other things I've got wrong about the code base.
=> feat(storage): Support composite primary keys

.gitignore, src/binder/create_function.rs, src/binder/mod.rs, src/catalog/function.rs, src/catalog/mod.rs, src/catalog/schema.rs, src/planner/explain.rs, src/planner/mod.rs
As titled, as a preparation for sql (and maybe more...) udf.
Currently `FunctionCatalog` stores fairly simple things: 
- function name
- argument types
- return type of the function
- the language used by function definition
- function body (i.e., the actual definition)
cc @wangrunji0408.
=> feat(catalog): add function catalog

src/binder/create_function.rs, src/binder/expr.rs, src/binder/mod.rs, src/catalog/function.rs, src/catalog/root.rs, src/catalog/schema.rs, src/executor/create_function.rs, src/executor/mod.rs
As titled, cc @wangrunji0408.
P.S. Some of the logic in `bind_create_function` is the same as `create_sql_function`. 😄
=> feat(function): add `CreateFunctionExecutor` & `bind_create_function`

src/binder/expr.rs, src/binder/mod.rs, tests/sql/sql_udf.slt
A minimal support for sql udf with unnamed parameters.
=> feat(binder): support sql udf with unnamed parameters

src/binder/delete.rs, src/binder/expr.rs, src/binder/mod.rs, src/binder/select.rs, src/binder/table.rs, src/planner/rules/plan.rs, tests/sql/cte.slt
This PR adds support for specifying CTEs using the `WITH` clause. We treat CTEs just as named subqueries. The implementation simply adds CTE queries to the binder context and inlines them when referenced.
However, due to an optimizer bug (which has been fixed in #796), the current CTE is pretty useless as most practice use cases will lead to panics.
=> feat: support WITH clause

Cargo.lock, Cargo.toml, src/array/mod.rs, src/binder/copy.rs, src/binder/create_table.rs, src/binder/create_view.rs, src/binder/delete.rs, src/binder/drop.rs, src/binder/insert.rs, src/binder/mod.rs, src/binder/table.rs, src/catalog/root.rs, src/catalog/schema.rs, src/catalog/table.rs, src/db.rs, src/executor/copy_from_file.rs, src/executor/copy_to_file.rs, src/executor/create_table.rs, src/executor/create_view.rs, src/executor/drop.rs, src/executor/error.rs, src/executor/mod.rs, src/executor/system_table_scan.rs, src/planner/explain.rs, src/planner/mod.rs, src/storage/memory/mod.rs, src/storage/secondary/manifest.rs, tests/sql/view.slt
This PR is a part of #796, adds support for creating, querying and dropping views in memory.
The key implementations are: 
1. When creating a view, bind the query and store the logical plan with the view in catalog.
2. When querying from a view, build executors for all views and then build other plan nodes on top of them. Given that a view can be consumed by multiple downstream nodes, we introduce `StreamSubscriber` to allow multiple consumers of a stream.
Limitations:
1. We don't persist views in disk storage.
2. We don't support inferring schema from the query. Columns must be defined explicitly when creating a view.
3. We don't maintain dependency relationship between tables and views.
=> feat: support view in memory

src/binder/table.rs, src/executor/mod.rs, src/planner/rules/range.rs, tests/planner_test/count.planner.sql, tests/planner_test/extract-common-predicate.planner.sql, tests/planner_test/storage-pushdown.planner.sql, tests/planner_test/storage-pushdown.yml, tests/planner_test/tpch.planner.sql
Add a new rule that maps null to true so that storage filter on pk can be pushed down.
=> fix(optimizer): support pushdown pk to storage scan

src/planner/rules/expr.rs, tests/planner_test/storage-pushdown.planner.sql
related  to #794 #834 , add some new rules and change scan's default filter to true(this make it match with the "filter-scan" rule)
=> fix(optimizer): fix filter pushdown and range fold

Cargo.lock, Cargo.toml, src/array/ops.rs, src/binder/create_table.rs, src/binder/create_view.rs, src/binder/delete.rs, src/db.rs, src/executor/evaluator.rs, src/lib.rs, src/main.rs, src/server/processor.rs, src/types/date.rs, src/types/timestamp.rs, tests/sql/copy/csv.slt, tests/sql/substring.slt, tests/sqllogictest.rs
=> chore(deps): update dependencies

.github/workflows/bench.yml, .github/workflows/ci.yml, Cargo.toml, src/array/bytes_array.rs, src/array/data_chunk_builder.rs, src/array/primitive_array.rs, src/executor/hash_join.rs
In `HashSemiJoinExecutor2`, data chunk builder for each key was reserved with 1024 capacity. But they only have 4 rows on average in TPC-Q Q21. Therefore, more than `4*1020*2*1500000 = 12GB` memory was wasted.
This PR fixes this bug by using `DataChunkBuilder` with dynamic capacity. This PR also replaces vectors by boxed slices in array, making sure that unused memory is released after build. Finally, it enables q21 in CI.
```
run-q21                 time:   [2.6544 s 2.6956 s 2.7059 s]
change: [-61.787% -61.416% -61.045%] (p = 0.05 < 0.05)
```
=> fix: fix out-of-memory in tpch q21

src/planner/rules/plan.rs
I noticed that risinglight uses egg for CBO optimization, but it looks violent at the moment. I will try to optimize it.
=> chore: add rule and test

Cargo.lock, Cargo.toml, src/binder/mod.rs, src/executor/analyze.rs, src/executor/explain.rs, src/executor/mod.rs, src/planner/explain.rs, src/planner/mod.rs, src/utils/mod.rs, src/utils/timed.rs
Inspired by duckdb's [EXPLAIN ANALYZE](https://duckdb.org/docs/guides/meta/explain_analyze.html).
<details>
<summary>Example of TPCH Q6</summary>
```sql
explain analyze select
sum(l_extendedprice * l_discount) as revenue
from
lineitem
where
l_shipdate >= date '1994-01-01'
and l_shipdate < date '1994-01-01' + interval '1' year
and l_discount between 0.08 - 0.01 and 0.08 + 0.01
and l_quantity < 24;
Projection
├── exprs:ref
│   └── sum
│       └── * { lhs: l_discount, rhs: l_extendedprice }
├── rows: 1
├── time: 91.042µs
└── Agg
├── aggs:sum
│   └── * { lhs: l_discount, rhs: l_extendedprice }
├── rows: 1
├── time: 4.525204ms
└── Filter
├── cond: and { lhs: >= { lhs: 0.09, rhs: l_discount }, rhs: >= { lhs: l_discount, rhs: 0.07 } }
├── rows: …
```
=> feat: support `EXPLAIN ANALYZE` to profile queries

src/db.rs, src/main.rs
Support keyword completion in the builtin shell. Press tab to try it out!
=> feat: support keyword completion

.github/workflows/ci.yml, src/main.rs
To keep consistent with sqlite and duckdb:
```sh
risinglight # use in-memory storage
risinglight test.db # use disk storage
```
=> feat: use in-memory storage by default

src/binder/copy.rs, src/binder/create_function.rs, src/binder/create_table.rs, src/binder/create_view.rs, src/binder/delete.rs, src/binder/drop.rs, src/binder/error.rs, src/binder/expr.rs, src/binder/insert.rs, src/binder/mod.rs, src/binder/select.rs, src/binder/table.rs, src/db.rs, src/planner/explain.rs, src/planner/mod.rs, src/types/value.rs
Sqlparser introduced [span](https://docs.rs/sqlparser/latest/sqlparser/index.html#source-spans) since v0.53. This PR utilizes span to improve error reporting.
```
> create table t(a int);
> select b from t;
bind error: invalid column "b"
LINE 1: select b from t;
^
```
=> feat(error): highlight bind error location

src/binder/create_index.rs, src/binder/error.rs, src/binder/mod.rs, src/catalog/index.rs, src/catalog/mod.rs, src/catalog/root.rs, src/catalog/schema.rs, src/db.rs, src/executor/create_index.rs, src/executor/mod.rs, src/executor/system_table_scan.rs, src/planner/explain.rs, src/planner/mod.rs, src/storage/index/mod.rs, src/storage/memory/mod.rs, src/storage/mod.rs, src/storage/secondary/mod.rs, src/storage/secondary/storage.rs, tests/sql/catalog.slt
part of https://github.com/risinglightdb/risinglight/issues/864
Add `create index` support. No indexes are created for now. It only modifies the catalog. All storage engines now use a shared submodule called `index` to manage in-memory indexes.
=> feat(binder): support create index statements

src/array/chunked_array.rs, src/array/mod.rs, src/array/var_array.rs, tests/sql/vector.slt
requires: https://github.com/risinglightdb/risinglight/pull/866
This patch adds a new array type for vector arrays.
The array stores primitive type chunks of the same length. Trying to inserting chunks of different sizes will panic.
https://github.com/risinglightdb/risinglight/issues/864
=> feat(array): use fixed chunk array for vectors

src/array/ops.rs, src/binder/expr.rs, src/executor/evaluator.rs, src/planner/explain.rs, src/planner/mod.rs, src/planner/rules/type_.rs, tests/sql/repeat.slt
Partly fixed #387.
- support `repeat` function
- add sqllogictest for `repeat`
**WIP**: support `trim`, `length`, `lower`, `upper`.
=> feat(expression): support repeat function
